/**
 * @description       : Test class for SIB_LoggingConstantTest
 * @author            : Jeetendranath Jakkamsetti
 * @group             : 
 * @last modified on  : 11-05-2024
 * @last modified by  : Jeetendranath Jakkamsetti
**/
@isTest
public class SIB_LoggingConstantTest {
    @isTest
    static void testGetCartByIds(){
        Test.startTest();
        SIB_LoggingConstant testInstance = new SIB_LoggingConstant();
        Test.stopTest();
    }
}