/**
 * Created by junaidmohammed on 10/25/24.
 */

public with sharing class SIB_LoggingConstant {

    //B2B Exception Variables
    public static final String MESSAGING_LOG = 'log';
    public static final String MESSAGING_ENTRY = '[M:E]:';
    public static final String MESSAGING_EXIT = '[M:X]:';
    public static final String MESSAGING_VALUE = '[M:V]:';
    public static final String USER_TYPE_GUEST = 'Guest';
}